# -*- coding: utf-8 -*-
"""01a_extraccion_geolocalizada.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1anrkF15S5KpkVvmJDdgXVxV4i1Eri3-d
"""

from google.colab import drive
import os
import requests
import time
import pandas as pd
import json
import calendar
import re
import glob

drive.mount('/content/drive')

CARPETA_DESTINO = '/content/drive/MyDrive/TU_CARPETA'
if not os.path.exists(CARPETA_DESTINO):
    os.makedirs(CARPETA_DESTINO)

API_KEY = "TU_API_KEY"

GRUPOS_KEYWORDS = {
    "1": ["anorexia", "bulimia", "tca", '"trastorno alimenticio"', "probulimia", "proanorexia"],
    "2": ["proana", "promia", "edtwt", "thinspo", "bonespo", "ugw", "cw", "bmi", "imc", "edtw"],
    "3": ["binge", "purge", "atracon", "atracón", '"me siento gorda"', '"me veo gorda"']
}

LANG = "es"
lat = "40.4168"
long = "-3.7038"
radius = "600km"
WAIT_TIME = 30

def fetch_all_tweets(query: str, api_key: str):
    base_url = "https://api.twitterapi.io/twitter/tweet/advanced_search"
    headers = {"x-api-key": api_key}
    all_tweets = []
    seen_tweet_ids = set()
    cursor = None
    last_min_id = None
    max_retries = 3
    page_count = 0
    max_pages = 60

    while True:
        params = {"query": query}
        if cursor: params["cursor"] = cursor
        elif last_min_id: params["query"] = f"{query} max_id:{last_min_id}"

        retry_count = 0
        while retry_count < max_retries:
            try:
                response = requests.get(base_url, headers=headers, params=params)
                response.raise_for_status()
                data = response.json()
                tweets = data.get("tweets", [])
                has_next_page = data.get("has_next_page", False)
                cursor = data.get("next_cursor", None)

                new_tweets = [t for t in tweets if t.get("id") not in seen_tweet_ids]
                for tweet in new_tweets:
                    seen_tweet_ids.add(tweet.get("id"))
                    all_tweets.append(tweet)

                page_count += 1
                if page_count >= max_pages or not tweets: return all_tweets
                if new_tweets: last_min_id = new_tweets[-1].get("id")
                if not has_next_page: return all_tweets
                break
            except Exception as e:
                retry_count += 1
                if retry_count == max_retries: return all_tweets
                time.sleep(2 ** retry_count)
    return all_tweets

def parse_tweets(tweets):
    return [{"text": t.get("text"), "createdAt": t.get("createdAt"), "id": t.get("id"),
             "userName": t.get("author", {}).get("userName"), "location": t.get("author", {}).get("location"),
             "likes": t.get("likeCount"), "lang": t.get("lang")} for t in tweets]

def generate_date_ranges(start_year, end_year):
    ranges = []
    for year in range(start_year, end_year + 1):
        for month in range(1, 13):
            days = calendar.monthrange(year, month)[1]
            ranges.append((f"{year}-{month:02d}-01", f"{year}-{month:02d}-{days:02d}"))
    return ranges

def main():
    date_ranges = generate_date_ranges(2020, 2025)

    for i, (start_date, end_date) in enumerate(date_ranges, 1):
        print(f"GEO ({i}/{len(date_ranges)}): {start_date}...")
        mes_raw = []

        for _, lista_keywords in GRUPOS_KEYWORDS.items():
            query = f"({' OR '.join(lista_keywords)}) lang:{LANG} since:{start_date} until:{end_date} geocode:{lat},{long},{radius}"
            mes_raw.extend(fetch_all_tweets(query, API_KEY))

        df = pd.DataFrame(parse_tweets(mes_raw))
        if not df.empty:
            df = df.drop_duplicates(subset=["id"])
            patron_ok = r"\b(el|la|de|que|y|no|me|es|en|un|una|con|por|si|mi|cw|ugw|hw|kg|imc|bmi|tca|edtwt|ana|mia|thinspo)\b"
            df = df[(df["lang"] == "es") & (df["text"].str.contains(patron_ok, case=False, na=False, regex=True))]

if __name__ == "__main__":
    main()