# -*- coding: utf-8 -*-
"""01b_extraccion_filtros_linguisticos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1--RHwfUlplmbL32pwc776f5ZMjXaMXXU
"""

from google.colab import drive
import os
import requests
import time
import pandas as pd
import json
import calendar
import re
import glob

drive.mount('/content/drive')

CARPETA_DESTINO = '/content/drive/MyDrive/TU_CARPETA'
if not os.path.exists(CARPETA_DESTINO):
    os.makedirs(CARPETA_DESTINO)

API_KEY = "TU_API_KEY"

GRUPOS_KEYWORDS = {
    "1": ["anorexia", "bulimia", "tca", '"trastorno alimenticio"', "probulimia", "proanorexia"],
    "2": ["proana", "promia", "edtwt", "thinspo", "bonespo", "ugw", "cw", "bmi", "imc", "edtw"],
    "3": ["binge", "purge", "atracon", "atracón", '"me siento gorda"', '"me veo gorda"']
}

LANG = "es"
WAIT_TIME = 30
def fetch_all_tweets(query: str, api_key: str):
    base_url = "https://api.twitterapi.io/twitter/tweet/advanced_search"
    headers = {"x-api-key": api_key}
    all_tweets = []
    seen_tweet_ids = set()
    cursor = None
    last_min_id = None
    max_retries = 3
    page_count = 0
    max_pages = 60

    while True:
        params = {"query": query}
        if cursor: params["cursor"] = cursor
        elif last_min_id: params["query"] = f"{query} max_id:{last_min_id}"

        retry_count = 0
        while retry_count < max_retries:
            try:
                response = requests.get(base_url, headers=headers, params=params)
                response.raise_for_status()
                data = response.json()
                tweets = data.get("tweets", [])
                has_next_page = data.get("has_next_page", False)
                cursor = data.get("next_cursor", None)

                new_tweets = [t for t in tweets if t.get("id") not in seen_tweet_ids]
                for tweet in new_tweets:
                    seen_tweet_ids.add(tweet.get("id"))
                    all_tweets.append(tweet)

                page_count += 1
                if page_count >= max_pages or not tweets:
                    return all_tweets

                if new_tweets: last_min_id = new_tweets[-1].get("id")
                if not has_next_page: return all_tweets
                break

            except Exception as e:
                retry_count += 1
                if retry_count == max_retries: return all_tweets
                time.sleep(2 ** retry_count)
    return all_tweets

def parse_tweets(tweets, keywords_str):
    parsed = []
    for tweet in tweets:
        author = tweet.get("author", {})
        parsed.append({
            "text": tweet.get("text"),
            "createdAt": tweet.get("createdAt"),
            "id": tweet.get("id"),
            "userName": author.get("userName"),
            "location": author.get("location"),
            "likes": tweet.get("likeCount"),
            "lang": tweet.get("lang"),
            "keywords": keywords_str
        })
    return parsed

def generate_date_ranges(start_year, end_year):
    ranges = []
    for year in range(start_year, end_year + 1):
        for month in range(1, 13):
            days = calendar.monthrange(year, month)[1]
            ranges.append((f"{year}-{month:02d}-01", f"{year}-{month:02d}-{days:02d}"))
    return ranges

def main():
    date_ranges = generate_date_ranges(2020, 2025)

    for i, (start_date, end_date) in enumerate(date_ranges, 1):
        print(f"LANG ({i}/{len(date_ranges)}): {start_date}...")
        mes_tweets_acumulados = []

        for nombre_grupo, lista_keywords in GRUPOS_KEYWORDS.items():
            query = " OR ".join(lista_keywords) + f" lang:{LANG} since:{start_date} until:{end_date}"

            raw_tweets = fetch_all_tweets(query, API_KEY)
            mes_tweets_acumulados.extend(raw_tweets)

        df = pd.DataFrame(parse_tweets(mes_tweets_acumulados, "MULTI-GRUPO"))

        if not df.empty:
            df = df.drop_duplicates(subset=["id"])
            patron_permitido = r"\b(el|la|de|que|y|no|me|es|en|un|una|con|por|si|mi)\b"
            df = df[(df["lang"] == "es") & (df["text"].str.contains(patron_permitido, case=False, na=False, regex=True))]

            latam_slang = r"\b(wey|weon|weón|vos|che|chido|plata|carro|celular|computadora|enojad[ao]|neta|ahorita|chabona|pendej[ao]|pinche|conchetumare|qliao|parcero|parce|chucha|pololo|platicar|nomás|nomadas|verga|mmg|acá|aca|vrg)\b"
            df = df[~df["text"].str.contains(latam_slang, case=False, na=False, regex=True)]

            paises_latam = r"\b(méxico|mexico|cdmx|monterrey|argentina|caba|buenos aires|colombia|bogotá|bogota|medellin|chile|santiago|perú|peru|lima|ecuador|quito|venezuela|caracas|guatemala|bolivia|honduras|paraguay|uruguay|costa rica|panamá|panama|puerto rico|dominicana|el salvador|nicaragua|latam)\b"
            df = df[df["location"].isnull() | ~df["location"].str.contains(paises_latam, case=False, na=False, regex=True)]

        filename = f"{CARPETA_DESTINO}/tweets_TCA_LANG_{start_date}_{end_date}.csv"
        df.to_csv(filename, index=False)
        print(f"   -> Guardados: {len(df)} tweets")
        time.sleep(WAIT_TIME)

if __name__ == "__main__":
    main()