# -*- coding: utf-8 -*-
"""02_unificacion_y_limpieza.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qG_6tHRfr1WB2TKIRe8BIYDrf5WPXhxI
"""

import pandas as pd
import glob

def main():

    CARPETA_DESTINO = '/content/drive/MyDrive/TU_CARPETA'
    archivos_csv = glob.glob(f"{CARPETA_DESTINO}/tweets_TCA*.csv")

    lista_dfs = []
    for archivo in archivos_csv:
        try:
            df_temp = pd.read_csv(archivo)
            if df_temp.empty: continue

            if "_GEO_" in archivo:
                df_temp["metodo_extraccion"] = "Geolocalizacion_GPS"
            else:
                df_temp["metodo_extraccion"] = "Filtros_Linguisticos"

            lista_dfs.append(df_temp)
            print(f"{archivo.split('/')[-1]} ({len(df_temp)} tweets)")
        except Exception as e:
            print(f"Error: {e}")

    df_final = pd.concat(lista_dfs, ignore_index=True)
    df_final = df_final.dropna(subset=["id", "text"])
    df_final = df_final.drop_duplicates(subset=["id"], keep="first")
    df_final = df_final[df_final["text"].str.len() > 10]

    nombre_salida = f"{CARPETA_DESTINO}/DATASET_FINAL_MAESTRO.csv"
    df_final.to_csv(nombre_salida, index=False)

if __name__ == "__main__":
    main()