# -*- coding: utf-8 -*-
"""03_filtro_instituciones_vs_usuarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iz_j_UHS6acrjxaM9ND-cSp0D6rVSadn
"""

import os
import time
import requests
import numpy as np
import pandas as pd

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report
from datasets import Dataset
from transformers import AutoTokenizer, AutoModelForSequenceClassification, TrainingArguments, Trainer
import evaluate

API_KEY = "TU_API_KEY_AQUI"
CARPETA_DESTINO = '/content/drive/MyDrive/TU_CARPETA'

def main():
    print("FASE 3: FILTRO DE INSTITUCIONES VS USUARIOS")

    archivo_maestro = f"{CARPETA_DESTINO}/DATASET_FINAL_MAESTRO.csv"
    archivo_unicos = f"{CARPETA_DESTINO}/usuarios_unicos.csv"
    archivo_perfiles = f"{CARPETA_DESTINO}/usuarios_perfiles.csv"

    print("[1/4] Identificando usuarios únicos...")
    df = pd.read_csv(archivo_maestro)
    usuarios = df[["userName"]].drop_duplicates()
    usuarios.to_csv(archivo_unicos, index=False)
    print(f"-> Encontrados {len(usuarios)} usuarios únicos.")

    print("[2/4] Descargando biografías desde la API de Twitter...")
    perfiles = []
    headers = {"x-api-key": API_KEY}
    url_api = "https://api.twitterapi.io/twitter/user/info"

    for i, username in enumerate(usuarios["userName"], 1):
        try:
            response = requests.get(url_api, headers=headers, params={"userName": username})
            data = response.json().get("data", {})

            perfiles.append({
                "userName": username,
                "id": data.get("id"),
                "name": data.get("name"),
                "description": data.get("description"),
                "location": data.get("location"),
                "followers": data.get("followers")
            })
            time.sleep(1)
        except Exception as e:
            pass

    df_perfiles = pd.DataFrame(perfiles)
    df_perfiles.to_csv(archivo_perfiles, index=False)
    print(f"-> Perfiles descargados exitosamente: {len(df_perfiles)}")

    archivo_manual = f"{CARPETA_DESTINO}/sample_400_clasificacion_manual.csv"

    if not os.path.exists(archivo_manual):
        print(f"ESPERANDO INTERVENCIÓN HUMANA: Faltan los 400 perfiles etiquetados manualmente en {archivo_manual}")
        return

    print("[3/4] Entrenando Modelo de Lenguaje (BERT)")
    df_train = pd.read_csv(archivo_manual)
    df_train["texto"] = (df_train["name"].fillna("") + " " + df_train["description"].fillna("")).str.lower()

    df_train = df_train.dropna(subset=["tipo_manual"]).copy()
    df_train["tipo_manual"] = df_train["tipo_manual"].astype(str).str.strip().str.lower()
    df_train = df_train[df_train["tipo_manual"].isin(["usuario", "empresa"])].copy()

    label_map = {"usuario": 0, "empresa": 1}
    df_train["label"] = df_train["tipo_manual"].map(label_map)

    train_df, test_df = train_test_split(df_train, test_size=0.2, random_state=42, stratify=df_train["label"])

    train_dataset = Dataset.from_pandas(train_df[["texto", "label"]])
    test_dataset = Dataset.from_pandas(test_df[["texto", "label"]])

    MODEL_NAME = "dccuchile/bert-base-spanish-wwm-cased"
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME, num_labels=2)

    def tokenize(batch):
        return tokenizer(batch["texto"], padding=True, truncation=True, max_length=128)

    train_dataset = train_dataset.map(tokenize, batched=True)
    test_dataset = test_dataset.map(tokenize, batched=True)

    accuracy_metric = evaluate.load("accuracy")

    def compute_metrics(eval_pred):
        logits, labels = eval_pred
        predictions = np.argmax(logits, axis=-1)
        return accuracy_metric.compute(predictions=predictions, references=labels)

    training_args = TrainingArguments(
        output_dir="./results",
        eval_strategy="epoch",
        save_strategy="epoch",
        num_train_epochs=3,
        per_device_train_batch_size=8,
        per_device_eval_batch_size=8,
        learning_rate=2e-5,
        weight_decay=0.01
    )

    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=train_dataset,
        eval_dataset=test_dataset,
        compute_metrics=compute_metrics
    )


    trainer.train()
    print("Métricas del modelo sobre el conjunto de test:")
    test_preds = np.argmax(trainer.predict(test_dataset).predictions, axis=-1)
    print(classification_report(test_df["label"], test_preds))

    print("[4/4] Aplicando IA y heurística al corpus total...")
    usuarios = pd.read_csv(archivo_perfiles)
    usuarios["texto"] = (usuarios["name"].fillna("") + " " + usuarios["description"].fillna("")).str.lower()

    usuarios_dataset = Dataset.from_pandas(usuarios[["texto"]]).map(tokenize, batched=True)
    preds = np.argmax(trainer.predict(usuarios_dataset).predictions, axis=-1)

    reverse_map = {0: "usuario", 1: "empresa"}
    usuarios["tipo_cuenta"] = [reverse_map[p] for p in preds]

    PALABRAS_EMPRESA = [
        "asociación", "fundación", "hospital", "clínica", "universidad",
        "ong", "periódico", "revista", "federación", "instituto", "centro",
        "organización", "empresa", "medio", "association", "foundation",
        "sin ánimo de lucro", "entidad", "prevención", "tratamiento",
        "profesionales", "servicio", "atención", "salud mental"
    ]

    usuarios["description"] = usuarios["description"].fillna("").astype(str).str.lower()
    mask_empresa = usuarios["description"].str.contains("|".join(PALABRAS_EMPRESA), na=False)
    usuarios.loc[mask_empresa, "tipo_cuenta"] = "empresa"

    usuarios.to_csv(f"{CARPETA_DESTINO}/usuarios_clasificados.csv", index=False)

    usuarios_final = usuarios[usuarios["tipo_cuenta"] == "usuario"]
    archivo_final = f"{CARPETA_DESTINO}/DATASET_FINAL_USUARIOS.csv"
    usuarios_final.to_csv(archivo_final, index=False)

    print("\n" + "="*50)
    print("FASE 3 COMPLETADA CON ÉXITO")
    print(f"Distribución final: {usuarios['tipo_cuenta'].value_counts()}")
    print(f"Guardados {len(usuarios_final)} usuarios reales en: {archivo_final}")
    print("="*50)

if __name__ == "__main__":
    main()