# -*- coding: utf-8 -*-
"""04_extraccion_historial_usuarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1H6NSOLaSv8iXSJWiGiNNsGTNfT0gvl8p
"""

from google.colab import drive
import os
import requests
import time
import pandas as pd
import re

drive.mount('/content/drive')


API_KEY = "TU_API_KEY"

CARPETA_DESTINO = '/content/drive/MyDrive/TU_CARPETA'
ARCHIVO_MAESTRO = f'{CARPETA_DESTINO}/DATASET_FINAL_USUARIOS.csv'
ARCHIVO_SALIDA_BRUTO = f'{CARPETA_DESTINO}/HISTORIAL_USUARIOS_TCA_DEF.csv'

WAIT_TIME = 2
MAX_TWEETS = 50


def limpiar(texto):
    """Limpia URLs y menciones para un texto más legible."""
    texto = re.sub(r'http\S+', '', str(texto))
    texto = re.sub(r'@\w+', '', texto)
    return texto.strip()


def fetch_user_last_original_tweets(username: str, api_key: str):
    """Descarga solo los tweets originales del usuario (sin RTs ni respuestas)."""
    base_url = "https://api.twitterapi.io/twitter/tweet/advanced_search"
    headers = {
        "x-api-key": api_key
    }


    params = {
        "query": f"from:{username} -filter:replies -filter:retweets"
    }

    try:
        response = requests.get(base_url, headers=headers, params=params)
        response.raise_for_status()
        data = response.json()
        tweets = data.get("tweets", [])

        return tweets[:MAX_TWEETS]

    except Exception as e:
        print(f"Error o perfil privado con @{username}")
        return []


def parse_tweets(tweets, username):
    """Extrae los campos que nos interesan de la respuesta JSON."""
    parsed = []
    for tweet in tweets:
        parsed.append({
            "usuario_objetivo": username,
            "text": limpiar(tweet.get("text")),
            "createdAt": tweet.get("createdAt"),
            "id": tweet.get("id"),
            "likes": tweet.get("likeCount"),
            "lang": tweet.get("lang")
        })
    return parsed


def main():
    print("INICIANDO EXTRACCIÓN DE HISTORIALES (TWEETS ORIGINALES)")
    if os.path.exists(ARCHIVO_SALIDA_BRUTO):
        os.remove(ARCHIVO_SALIDA_BRUTO)
        print("Archivo de la sesión anterior detectado y eliminado. Empezando extracción desde cero.")

    if not os.path.exists(ARCHIVO_MAESTRO):
        print(f"Error: No se encuentra el archivo maestro en {ARCHIVO_MAESTRO}")
        return

    df_maestro = pd.read_csv(ARCHIVO_MAESTRO)
    usuarios_unicos = df_maestro['userName'].dropna().unique()
    print(f"Total de usuarios únicos a procesar: {len(usuarios_unicos)}")
    usuarios_procesados = set()
    if os.path.exists(ARCHIVO_SALIDA_BRUTO):
        df_existente = pd.read_csv(ARCHIVO_SALIDA_BRUTO)
        usuarios_procesados = set(df_existente['usuario_objetivo'].unique())
        print(f"Retomando sesión: {len(usuarios_procesados)} usuarios ya procesados.")

    usuarios_pendientes = [u for u in usuarios_unicos if u not in usuarios_procesados]

    if not usuarios_pendientes:
        print(" No hay usuarios pendientes por descargar.")
        return

    nuevos_tweets = []
    contador_guardado = 0

    for i, usuario in enumerate(usuarios_pendientes, 1):
        print(f"[{i}/{len(usuarios_pendientes)}] Extrayendo perfil de: @{usuario}")

        raw_tweets = fetch_user_last_original_tweets(usuario, API_KEY)

        if raw_tweets:
            parsed = parse_tweets(raw_tweets, usuario)
            nuevos_tweets.extend(parsed)

        contador_guardado += 1
        time.sleep(WAIT_TIME)

        if contador_guardado % 50 == 0 or i == len(usuarios_pendientes):
            if nuevos_tweets:
                df_nuevos = pd.DataFrame(nuevos_tweets)
                if os.path.exists(ARCHIVO_SALIDA_BRUTO):
                    df_existente = pd.read_csv(ARCHIVO_SALIDA_BRUTO)
                    df_final = pd.concat([df_existente, df_nuevos], ignore_index=True)
                else:
                    df_final = df_nuevos

                df_final.to_csv(ARCHIVO_SALIDA_BRUTO, index=False)
                print(f"Progreso guardado. Total acumulado: {len(df_final)} tweets.")
                nuevos_tweets = []

    print("EXTRACCIÓN COMPLETADA.")

if __name__ == "__main__":
    main()

from google.colab import drive
drive.mount('/content/drive', force_remount=True)

import pandas as pd

# Leemos el archivo bruto que generó la celda anterior
df = pd.read_csv("/content/drive/MyDrive/TFM/HISTORIAL_USUARIOS_TCA_DEF.csv")

# Agrupamos los tweets por usuario
usuarios = (
    df.groupby("usuario_objetivo", sort=False)
      .agg({
          "text": lambda x: "\n\n".join(
              [f"Tweet {i+1}:\n{t}" for i, t in enumerate(x)]
          )
      })
      .reset_index()
)

# Renombramos la columna
usuarios.rename(
    columns={"text": "historial"},
    inplace=True
)

# Guardamos el resultado final agrupado
usuarios.to_csv(
    "/content/drive/MyDrive/TFM/USUARIOS_AGRUPADOS_TCA_DEF.csv",
    index=False
)

# Imprimimos el resumen tal cual lo tenías
print(f"Usuarios agrupados: {len(usuarios)}\n")
print(usuarios.head())

print("\n--- RESUMEN FINAL ---")
print("Tweets originales totales:", len(df))
print("Usuarios únicos:", df["usuario_objetivo"].nunique())
print("Filas tras agrupar:", len(usuarios))