# -*- coding: utf-8 -*-
"""05_anonimizador_usuarios.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1B4onRWLJxlFbVfQZCBgjpXNXCYE7HUtZ
"""

!pip install scrubadub

!pip install spacy
!python -m spacy download es_core_news_md

import pandas as pd
import re
import scrubadub
import spacy
from google.colab import drive


drive.mount('/content/drive')


CARPETA = "/content/drive/MyDrive/TU_CARPETA"

INPUT_FILE = f"{CARPETA}/USUARIOS_AGRUPADOS_TCA_DEF.csv"

OUTPUT_FILE = f"{CARPETA}/USUARIOS_AGRUPADOS_TCA_ANONIMIZADO.csv"

SPACY_MODEL = "es_core_news_md"


nlp = spacy.load(SPACY_MODEL)


def setup_scrubber():

    scrubber = scrubadub.Scrubber()

    return scrubber



def anonymize_locations_spacy(text):

    if not text:
        return text

    doc = nlp(text)

    new_text_parts = []

    last_idx = 0

    for ent in doc.ents:

        if ent.label_ in ("LOC", "GPE"):

            new_text_parts.append(
                text[last_idx:ent.start_char]
            )

            new_text_parts.append(
                "{{LOCATION}}"
            )

            last_idx = ent.end_char

    new_text_parts.append(
        text[last_idx:]
    )

    return "".join(new_text_parts)



def anonymize_persons_spacy(text):

    if not text:
        return text

    doc = nlp(text)

    new_text_parts = []

    last_idx = 0

    for ent in doc.ents:

        if ent.label_ in ("PER", "PERSON"):

            new_text_parts.append(
                text[last_idx:ent.start_char]
            )

            new_text_parts.append(
                "{{PERSON}}"
            )

            last_idx = ent.end_char

    new_text_parts.append(
        text[last_idx:]
    )

    return "".join(new_text_parts)



def anonymize_capitalized_name_phrases(text):

    if not text:
        return text

    pattern = r'\b([A-ZÁÉÍÓÚÑ][a-záéíóúñçü]+(?:\s+[A-ZÁÉÍÓÚÑ][a-záéíóúñçü]+)+)\b'

    return re.sub(
        pattern,
        "{{PERSON}}",
        text
    )



def extra_aggressive_clean(text):

    if not text:
        return text

    text = re.sub(
        r"https?://\S+|www\.\S+",
        "{{URL}}",
        text
    )

    text = re.sub(
        r"#\w+",
        "{{HASHTAG}}",
        text
    )

    text = re.sub(
        r"@\w+",
        "{{USER}}",
        text
    )

    text = re.sub(
        r"\d{3,}",
        "{{NUMBER}}",
        text
    )

    return text



def anonymize_text(scrubber, text):

    if pd.isna(text):
        return ""

    text = str(text).strip()

    if not text:
        return ""

    text = extra_aggressive_clean(text)

    text = anonymize_locations_spacy(text)

    text = anonymize_persons_spacy(text)

    text = anonymize_capitalized_name_phrases(text)

    text = scrubber.clean(text)

    return text



def main():

    df = pd.read_csv(INPUT_FILE)

    scrubber = setup_scrubber()

    df["historial_anon"] = df["historial"].apply(
        lambda x: anonymize_text(
            scrubber,
            x
        )
    )

    df = df.drop(
        columns=[
            "usuario_objetivo",
            "historial"
        ],
        errors="ignore"
    )

    df.to_csv(
        OUTPUT_FILE,
        index=False
    )

    print(
        "Usuarios anonimizados:",
        len(df)
    )

    print(
        "Archivo generado:",
        OUTPUT_FILE
    )


if __name__ == "__main__":

    main()