# -*- coding: utf-8 -*-
"""06_FineTuning_BERT_y_Clasificacion.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qc0E3nzfgqfT6biLT5xXNSP1FmqrtAb_
"""

import pandas as pd

CARPETA = "/content/drive/MyDrive/TFM_TWEETS/Datasets trabajados"

df = pd.read_csv(
    f"{CARPETA}/USUARIOS_AGRUPADOS_TCA_ANONIMIZADO.csv"
)

sample = df.sample(
    n=500,
    random_state=42
)

sample["tipo_manual"] = ""

sample.to_csv(
    f"{CARPETA}/SAMPLE_USUARIOS_RIESGO.csv",
    index=False
)

print("Archivo creado:")
print(f"{CARPETA}/SAMPLE_USUARIOS_RIESGO.csv")

print("Usuarios seleccionados:", len(sample))

!pip install transformers datasets accelerate evaluate -q

import pandas as pd
import numpy as np

from google.colab import drive

from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report

from datasets import Dataset

from transformers import (
    AutoTokenizer,
    AutoModelForSequenceClassification,
    TrainingArguments,
    Trainer
)

drive.mount('/content/drive')

CARPETA = "/content/drive/MyDrive/TU_CARPETA"

ARCHIVO_GOLD = f"{CARPETA}/SAMPLE_USUARIOS_RIESGO.csv"

ARCHIVO_TOTAL = f"{CARPETA}/USUARIOS_AGRUPADOS_TCA_ANONIMIZADO.csv"

ARCHIVO_SALIDA = f"{CARPETA}/USUARIOS_CLASIFICADOS_RIESGO.csv"

df = pd.read_csv(ARCHIVO_GOLD)

df = df.dropna(
    subset=["tipo_manual"]
).copy()

df["tipo_manual"] = (
    df["tipo_manual"]
    .str.lower()
    .str.strip()
)

label_map = {

    "control": 0,

    "dudoso": 1,

    "riesgo": 2

}

df["label"] = (
    df["tipo_manual"]
    .map(label_map)
)

df = df.dropna(
    subset=["label"]
)

df["label"] = (
    df["label"]
    .astype(int)
)

df = df.rename(
    columns={
        "historial_anon": "texto_modelo"
    }
)

print(df["tipo_manual"].value_counts())

train_df, test_df = train_test_split(

    df,

    test_size=0.2,

    random_state=42,

    stratify=df["label"]

)

train_dataset = Dataset.from_pandas(

    train_df[
        [
            "texto_modelo",
            "label"
        ]
    ]

)

test_dataset = Dataset.from_pandas(

    test_df[
        [
            "texto_modelo",
            "label"
        ]
    ]

)


MODEL = "dccuchile/bert-base-spanish-wwm-cased"

tokenizer = AutoTokenizer.from_pretrained(
    MODEL
)

model = AutoModelForSequenceClassification.from_pretrained(

    MODEL,

    num_labels=3

)


def tokenize(batch):

    return tokenizer(

        batch["texto_modelo"],

        padding=True,

        truncation=True,

        max_length=512

    )

train_dataset = train_dataset.map(
    tokenize,
    batched=True
)

test_dataset = test_dataset.map(
    tokenize,
    batched=True
)


training_args = TrainingArguments(

    output_dir="./LLM_TCA_Risk",

    eval_strategy="epoch",

    save_strategy="epoch",

    learning_rate=2e-5,

    per_device_train_batch_size=8,

    per_device_eval_batch_size=8,

    num_train_epochs=4,

    weight_decay=0.01

)

trainer = Trainer(

    model=model,

    args=training_args,

    train_dataset=train_dataset,

    eval_dataset=test_dataset

)

trainer.train()


predictions = trainer.predict(
    test_dataset
)

preds = np.argmax(

    predictions.predictions,

    axis=1

)

print(

    classification_report(

        test_df["label"],

        preds,

        target_names=[
            "control",
            "dudoso",
            "riesgo"
        ]

    )

)

df_total = pd.read_csv(
    ARCHIVO_TOTAL
)

df_total = df_total.rename(

    columns={
        "historial_anon": "texto_modelo"
    }

)

dataset_total = Dataset.from_pandas(

    df_total[
        [
            "texto_modelo"
        ]
    ]

)

dataset_total = dataset_total.map(

    tokenize,

    batched=True

)

predicciones_finales = trainer.predict(
    dataset_total
)

preds_final = np.argmax(

    predicciones_finales.predictions,

    axis=1

)

reverse_map = {

    0: "control",

    1: "dudoso",

    2: "riesgo"

}

df_total["LLM_TCA_Risk"] = [

    reverse_map[p]

    for p in preds_final

]

df_total.to_csv(

    ARCHIVO_SALIDA,

    index=False

)

print("\nArchivo generado:")
print(ARCHIVO_SALIDA)

print(df_total.head())