# -*- coding: utf-8 -*-
"""07_Analisis_Exploratorio_Resultados.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQtS59kdfGXOKyLHjTLtQNKBZQV09dCp

4.2 Distribución general del corpus clasificado
"""

import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

CARPETA = "/content/drive/MyDrive/TU_CARPETA"
df = pd.read_csv(f"{CARPETA}/USUARIOS_CLASIFICADOS_RIESGO.csv")

distribucion = df['LLM_TCA_Risk'].value_counts()
porcentajes = df['LLM_TCA_Risk'].value_counts(normalize=True) * 100

print("TABLA DE DISTRIBUCIÓN")
print(pd.DataFrame({'Total': distribucion, 'Porcentaje (%)': porcentajes.round(2)}))

plt.figure(figsize=(8, 6))

valores = [distribucion.get('control', 0), distribucion.get('riesgo', 0), distribucion.get('dudoso', 0)]
etiquetas = ['Control', 'Riesgo', 'Dudoso']

plt.pie(valores, labels=etiquetas, autopct='%1.1f%%',
        startangle=140, textprops={'fontsize': 12},
        wedgeprops={'edgecolor': 'white', 'linewidth': 2})

plt.title('Distribución del corpus de usuarios clasificados', fontsize=14, pad=20, fontweight='bold')

ruta_grafico = f"{CARPETA}/Figura_2_Distribucion_Usuarios.png"
plt.savefig(ruta_grafico, dpi=300, bbox_inches='tight')
plt.show()

print(f"Gráfico guardado")

"""4.3 Análisis discursivo y lingüístico de los perfiles de riesgo"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from wordcloud import WordCloud
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords
import re

nltk.download('stopwords')
base_stops = stopwords.words('spanish')


anon_y_ruido = [
    'rt', 'q', 'si', 'mas', 'xq', 'pq', 'https', 'co', 'no', 'por', 'que',
    'te', 'me', 'ya', 'se', 'lo', 'como', 'pero', 'del', 'al', 'sus',
    'tweet', 'hashtag', 'person', 'user', 'url', 'number', 'location',
    'd', 'm', 'x', 'k', 'y', 'a', 'o', 'e', 'i', 're', 'da', 'nan',"va"
]

verbos_comunes = [
    'quiero', 'ser', 'voy', 'hacer', 'hace', 'tan', 'hoy', 'solo', 'día', 'siento','ver', 'tener',
    'estoy', 'tengo', 'puedo', 'vez', 'bien', 'mal', 'muy', 'todos', 'todo', 'nada', 'así', 'ahora'
]


stop_words_relajada = base_stops + anon_y_ruido
stop_words_estricta = base_stops + anon_y_ruido + verbos_comunes


CARPETA = "/content/drive/MyDrive/TFM_TWEETS/Datasets trabajados"
df = pd.read_csv(f"{CARPETA}/USUARIOS_CLASIFICADOS_RIESGO.csv")


df_riesgo = df[df['LLM_TCA_Risk'] == 'riesgo'].copy()
df_control = df[df['LLM_TCA_Risk'] == 'control'].copy()

def get_top_ngrams(corpus, n=1, top_k=15, lista_stops=stop_words_estricta):
    vec = CountVectorizer(
        ngram_range=(n, n),
        stop_words=lista_stops,
        token_pattern=r"(?u)\b[a-zA-ZáéíóúÁÉÍÓÚñÑ]+\b"
    ).fit(corpus)

    bag_of_words = vec.transform(corpus)
    sum_words = bag_of_words.sum(axis=0)
    words_freq = [(word, sum_words[0, idx]) for word, idx in vec.vocabulary_.items()]
    words_freq = sorted(words_freq, key=lambda x: x[1], reverse=True)
    return words_freq[:top_k]

top_unigrams = get_top_ngrams(df_riesgo['texto_modelo'].dropna(), n=1, top_k=15, lista_stops=stop_words_estricta)
df_uni = pd.DataFrame(top_unigrams, columns=['Término', 'Frecuencia'])

plt.figure(figsize=(10, 6))
sns.barplot(x='Frecuencia', y='Término', data=df_uni)
plt.title('Top 15 Palabras Más Frecuentes - Perfiles de Riesgo', fontweight='bold', pad=15)
plt.tight_layout()
plt.savefig(f"{CARPETA}/Figura_3_Top15_Palabras_Riesgo.png", dpi=300)
plt.show()


top_bigrams = get_top_ngrams(df_riesgo['texto_modelo'].dropna(), n=2, top_k=15, lista_stops=stop_words_relajada)
df_bi = pd.DataFrame(top_bigrams, columns=['Bigrama', 'Frecuencia'])

plt.figure(figsize=(10, 6))
sns.barplot(x='Frecuencia', y='Bigrama', data=df_bi)
plt.title('Top 15 Pares de Palabras - Perfiles de Riesgo', fontweight='bold', pad=15)
plt.tight_layout()
plt.savefig(f"{CARPETA}/Figura_4_Top15_Bigramas_Riesgo.png", dpi=300)
plt.show()


def clean_for_wordcloud(text_series):

    text_list = [str(x) for x in text_series.dropna().tolist() if str(x).lower() != 'nan']
    text = " ".join(text_list)
    text = re.sub(r'\b\d+\b', '', text)
    return text

texto_riesgo = clean_for_wordcloud(df_riesgo['texto_modelo'])
texto_control = clean_for_wordcloud(df_control['texto_modelo'])

wc_riesgo = WordCloud(width=800, height=800, background_color='white', stopwords=stop_words_estricta).generate(texto_riesgo)
wc_control = WordCloud(width=800, height=800, background_color='white', stopwords=stop_words_estricta).generate(texto_control)

fig, ax = plt.subplots(1, 2, figsize=(16, 8))
ax[0].imshow(wc_control, interpolation='bilinear')
ax[0].axis('off')
ax[0].set_title('Grupo Control', fontsize=18, fontweight='bold')

ax[1].imshow(wc_riesgo, interpolation='bilinear')
ax[1].axis('off')
ax[1].set_title('Grupo Riesgo (TCA)', fontsize=18, fontweight='bold')
plt.tight_layout()
plt.savefig(f"{CARPETA}/Figura_5_WordClouds_Comparativas.png", dpi=300)
plt.show()