# -*- coding: utf-8 -*-
"""07_Caracterizacion_Discurso_Riesgo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cQtS59kdfGXOKyLHjTLtQNKBZQV09dCp

4.2 Distribución general del corpus clasificado
"""

import pandas as pd
import matplotlib.pyplot as plt

from google.colab import drive
drive.mount('/content/drive')

CARPETA = "/content/drive/MyDrive/TU_CARPETA"
df = pd.read_csv(f"{CARPETA}/USUARIOS_CLASIFICADOS_RIESGO.csv")

distribucion = df['LLM_TCA_Risk'].value_counts()
porcentajes = df['LLM_TCA_Risk'].value_counts(normalize=True) * 100

print("TABLA DE DISTRIBUCIÓN")
print(pd.DataFrame({'Total': distribucion, 'Porcentaje (%)': porcentajes.round(2)}))

plt.figure(figsize=(8, 6))

valores = [distribucion.get('control', 0), distribucion.get('riesgo', 0), distribucion.get('dudoso', 0)]
etiquetas = ['Control', 'Riesgo', 'Dudoso']

plt.pie(valores, labels=etiquetas, autopct='%1.1f%%',
        startangle=140, textprops={'fontsize': 12},
        wedgeprops={'edgecolor': 'white', 'linewidth': 2})

plt.title('Distribución del corpus de usuarios clasificados', fontsize=14, pad=20, fontweight='bold')

ruta_grafico = f"{CARPETA}/Figura_2_Distribucion_Usuarios.png"
plt.savefig(ruta_grafico, dpi=300, bbox_inches='tight')
plt.show()

"""4.3 Análisis discursivo y lingüístico de los perfiles de riesgo"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import nltk
from wordcloud import WordCloud
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords
import re

nltk.download('stopwords')
base_stops = stopwords.words('spanish')


anon_y_ruido = [
    'rt', 'q', 'si', 'mas', 'xq', 'pq', 'https', 'co', 'no', 'por', 'que',
    'te', 'me', 'ya', 'se', 'lo', 'como', 'pero', 'del', 'al', 'sus',
    'tweet', 'hashtag', 'person', 'user', 'url', 'number', 'location',
    'd', 'm', 'x', 'k', 'y', 'a', 'o', 'e', 'i', 're', 'da', 'nan',"va"
]

verbos_comunes = [
    'quiero', 'ser', 'voy', 'hacer', 'hace', 'tan', 'hoy', 'solo', 'día', 'siento','ver', 'tener',
    'estoy', 'tengo', 'puedo', 'vez', 'bien', 'mal', 'muy', 'todos', 'todo', 'nada', 'así', 'ahora'
]


stop_words_relajada = base_stops + anon_y_ruido
stop_words_estricta = base_stops + anon_y_ruido + verbos_comunes


CARPETA = "/content/drive/MyDrive/TFM_TWEETS/Datasets trabajados"
df = pd.read_csv(f"{CARPETA}/USUARIOS_CLASIFICADOS_RIESGO.csv")


df_riesgo = df[df['LLM_TCA_Risk'] == 'riesgo'].copy()
df_control = df[df['LLM_TCA_Risk'] == 'control'].copy()

def get_top_ngrams(corpus, n=1, top_k=15, lista_stops=stop_words_estricta):
    vec = CountVectorizer(
        ngram_range=(n, n),
        stop_words=lista_stops,
        token_pattern=r"(?u)\b[a-zA-ZáéíóúÁÉÍÓÚñÑ]+\b"
    ).fit(corpus)

    bag_of_words = vec.transform(corpus)
    sum_words = bag_of_words.sum(axis=0)
    words_freq = [(word, sum_words[0, idx]) for word, idx in vec.vocabulary_.items()]
    words_freq = sorted(words_freq, key=lambda x: x[1], reverse=True)
    return words_freq[:top_k]

top_unigrams = get_top_ngrams(df_riesgo['texto_modelo'].dropna(), n=1, top_k=15, lista_stops=stop_words_estricta)
df_uni = pd.DataFrame(top_unigrams, columns=['Término', 'Frecuencia'])

plt.figure(figsize=(10, 6))
sns.barplot(x='Frecuencia', y='Término', data=df_uni)
plt.title('Top 15 Palabras Más Frecuentes - Perfiles de Riesgo', fontweight='bold', pad=15)
plt.tight_layout()
plt.savefig(f"{CARPETA}/Figura_3_Top15_Palabras_Riesgo.png", dpi=300)
plt.show()


top_bigrams = get_top_ngrams(df_riesgo['texto_modelo'].dropna(), n=2, top_k=15, lista_stops=stop_words_relajada)
df_bi = pd.DataFrame(top_bigrams, columns=['Bigrama', 'Frecuencia'])

plt.figure(figsize=(10, 6))
sns.barplot(x='Frecuencia', y='Bigrama', data=df_bi)
plt.title('Top 15 Pares de Palabras - Perfiles de Riesgo', fontweight='bold', pad=15)
plt.tight_layout()
plt.savefig(f"{CARPETA}/Figura_4_Top15_Bigramas_Riesgo.png", dpi=300)
plt.show()

def clean_for_wordcloud(text_series):

    text_list = [str(x) for x in text_series.dropna().tolist() if str(x).lower() != 'nan']
    text = " ".join(text_list)
    text = re.sub(r'\b\d+\b', '', text)
    return text

texto_riesgo = clean_for_wordcloud(df_riesgo['texto_modelo'])
texto_control = clean_for_wordcloud(df_control['texto_modelo'])

wc_riesgo = WordCloud(width=800, height=800, background_color='white', stopwords=stop_words_estricta).generate(texto_riesgo)
wc_control = WordCloud(width=800, height=800, background_color='white', stopwords=stop_words_estricta).generate(texto_control)

fig, ax = plt.subplots(1, 2, figsize=(16, 8))
ax[0].imshow(wc_control, interpolation='bilinear')
ax[0].axis('off')
ax[0].set_title('Grupo Control', fontsize=18, fontweight='bold')

ax[1].imshow(wc_riesgo, interpolation='bilinear')
ax[1].axis('off')
ax[1].set_title('Grupo Riesgo (TCA)', fontsize=18, fontweight='bold')
plt.tight_layout()
plt.savefig(f"{CARPETA}/Figura_5_WordClouds_Comparativas.png", dpi=300)
plt.show()

import os
import re
import unicodedata
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.cm as cm

CARPETA = "/content/drive/MyDrive/TU_CARPETA"
ARCHIVO = f"{CARPETA}/USUARIOS_CLASIFICADOS_RIESGO.csv"

df = pd.read_csv(ARCHIVO)

col_texto = next((col for col in ["texto_modelo", "historial_anon", "historial", "text", "texto"] if col in df.columns), None)
col_clase = next((col for col in ["LLM_TCA_Risk", "clasificacion", "tipo_modelo", "prediccion", "categoria"] if col in df.columns), None)

def limpiar_texto(texto):
    if pd.isna(texto): return ""
    texto = str(texto).lower()
    texto = unicodedata.normalize("NFKD", texto)
    texto = "".join([c for c in texto if not unicodedata.combining(c)])
    texto = re.sub(r"http\S+|www\S+", " ", texto)
    texto = re.sub(r"@\w+", " ", texto)
    texto = re.sub(r"[^a-zA-Z0-9ñ\s]", " ", texto)
    return re.sub(r"\s+", " ", texto).strip()

df["texto_limpio"] = df[col_texto].apply(limpiar_texto)
df["categoria_limpia"] = df[col_clase].astype(str).str.lower().str.strip()
df["categoria_limpia"] = df["categoria_limpia"].replace({
    "perfil control": "control", "control ": "control",
    "perfil riesgo": "riesgo", "risk": "riesgo", "riesgo ": "riesgo",
    "perfil dudoso": "dudoso", "dudosa": "dudoso", "dudoso ": "dudoso"
})

df_riesgo = df[df["categoria_limpia"] == "riesgo"].copy()

senales_regex = {
    "Alimentación": [r"\bcomer\b", r"\bcomida\b", r"\bcomidas\b", r"\bcomido\b", r"\bcenar\b", r"\bcena\b", r"\bdesayuno\b", r"\bdesayunar\b", r"\bhambre\b", r"\bingesta\b", r"\bintake\b", r"\bkcal\b", r"\bkcals\b", r"\bcaloria\b", r"\bcalorias\b", r"\bcals\b", r"\blow cal\b", r"\blowcal\b"],
    "Peso/cuerpo": [r"\bpeso\b", r"\bpesar\b", r"\bpesarme\b", r"\bkilo\b", r"\bkilos\b", r"\bgorda\b", r"\bgordo\b", r"\bgordas\b", r"\bgordos\b", r"\bflaca\b", r"\bflaco\b", r"\bdelgada\b", r"\bdelgado\b", r"\bskinny\b", r"\bobesa\b", r"\bobeso\b", r"\bcuerpo\b", r"\bbarriga\b", r"\bpanza\b", r"\babdomen\b", r"\bcintura\b", r"\bpiernas\b", r"\bcostillas\b", r"\bclaviculas\b", r"\bgrasa\b", r"\bbodycheck\b", r"\bbody check\b", r"\bimc\b", r"\bbmi\b"],
    "Restricción": [r"\bayuno\b", r"\bayunar\b", r"\bayunando\b", r"\bfasting\b", r"\bomad\b", r"\bno comer\b", r"\bdejar comer\b", r"\bcomer menos\b", r"\brestringir\b", r"\brestriccion\b", r"\bdeficit\b", r"\bdieta\b", r"\bdiet\b", r"\bbajar peso\b", r"\bbajar kilos\b", r"\bperder peso\b", r"\badelgazar\b", r"\bengordar\b", r"\bsubir peso\b", r"\bpeso objetivo\b", r"\bugw\b", r"\bcw\b", r"\bgw\b"],
    "Malestar emocional": [r"\bodio\b", r"\bme odio\b", r"\basco\b", r"\bme da asco\b", r"\bculpa\b", r"\bculpable\b", r"\bansiedad\b", r"\btriste\b", r"\bdeprimida\b", r"\bdeprimido\b", r"\bllorar\b", r"\bquiero llorar\b", r"\bmierda\b", r"\bsufrir\b", r"\bsufrimiento\b", r"\btengo miedo\b", r"\bquiero morir\b"],
    "Comunidad TCA": [r"\bedtwt\b", r"\bedtw\b", r"\bproana\b", r"\bpro ana\b", r"\bpromia\b", r"\bpro mia\b", r"\bthinspo\b", r"\bbonespo\b", r"\bfatspo\b", r"\bmutis\b", r"\bmutuals\b", r"\btca\b", r"\banorexia\b", r"\banorexica\b", r"\banorexico\b", r"\bbulimia\b", r"\bana y mia\b", r"\bverdadera anorexia\b", r"\brecovery\b", r"\baccountability\b"],
    "Conductas compensatorias": [r"\bvomitar\b", r"\bvomito\b", r"\bvomite\b", r"\bpurge\b", r"\bpurgar\b", r"\blaxante\b", r"\blaxantes\b", r"\bcompensar\b", r"\bejercicio\b", r"\bhacer ejercicio\b", r"\bcardio\b", r"\bpilates\b", r"\bquemar calorias\b", r"\bpasos\b", r"\batracon\b", r"\batracones\b", r"\batracarme\b", r"\bbinge\b"]
}

def contiene_senal(texto, patrones):
    for patron in patrones:
        if re.search(patron, texto): return True
    return False

columnas_senales = list(senales_regex.keys())
for senal, patrones in senales_regex.items():
    df_riesgo[senal] = df_riesgo["texto_limpio"].apply(lambda x: contiene_senal(x, patrones))

matriz_conteos = pd.DataFrame(index=columnas_senales, columns=columnas_senales, dtype=float)
for s1 in columnas_senales:
    for s2 in columnas_senales:
        matriz_conteos.loc[s1, s2] = (df_riesgo[s1] & df_riesgo[s2]).sum()

np.fill_diagonal(matriz_conteos.values, np.nan)
matriz_porcentajes = (matriz_conteos / len(df_riesgo) * 100).round(2)

fig, ax = plt.subplots(figsize=(10, 8))
cmap = cm.get_cmap("GnBu").copy()
cmap.set_bad(color="white")
vmin, vmax = np.nanmin(matriz_porcentajes.values), np.nanmax(matriz_porcentajes.values)

im = ax.imshow(matriz_porcentajes.values, cmap=cmap, vmin=vmin, vmax=vmax)
ax.set_xticks(np.arange(len(columnas_senales)))
ax.set_yticks(np.arange(len(columnas_senales)))
ax.set_xticklabels(columnas_senales, rotation=45, ha="right")
ax.set_yticklabels(columnas_senales)

ax.set_xticks(np.arange(-0.5, len(columnas_senales), 1), minor=True)
ax.set_yticks(np.arange(-0.5, len(columnas_senales), 1), minor=True)
ax.grid(which="minor", color="white", linestyle="-", linewidth=2)
ax.tick_params(which="minor", bottom=False, left=False)

umbral = vmin + (vmax - vmin) * 0.55
for i in range(len(columnas_senales)):
    for j in range(len(columnas_senales)):
        valor = matriz_porcentajes.iloc[i, j]
        if pd.isna(valor):
            texto, color_texto = "-", "black"
        else:
            texto = f"{valor:.1f}%"
            color_texto = "white" if valor > umbral else "black"
        ax.text(j, i, texto, ha="center", va="center", fontsize=10, fontweight="bold", color=color_texto)

plt.title("Coocurrencias entre señales en perfiles de riesgo", fontsize=14, fontweight='bold', pad=15)
plt.colorbar(im).set_label("Porcentaje de perfiles de riesgo (%)")
plt.tight_layout()
plt.savefig(f"{CARPETA}/Figura_Coocurrencias_Riesgo.png", dpi=300)
plt.show()

import matplotlib.pyplot as plt
import numpy as np

CARPETA = "/content/drive/MyDrive/TU_CARPETA"

categorias = ['yo', 'me', 'mi / mí', 'mío / mía', 'conmigo', 'Total']
medias_control = [1.08, 3.90, 2.17, 0.12, 0.07, 7.33]
medias_riesgo = [1.46, 7.75, 3.84, 0.12, 0.08, 13.26]

x = np.arange(len(categorias))
ancho = 0.35

fig, ax = plt.subplots(figsize=(10, 6), dpi=300)

barras_control = ax.bar(x - ancho/2, medias_control, ancho, label='Grupo Control', color='#2b5c8f')
barras_riesgo = ax.bar(x + ancho/2, medias_riesgo, ancho, label='Grupo Riesgo (TCA)', color='#e07a5f')

ax.set_ylabel('Media de apariciones por usuario', fontsize=12, fontweight='bold', labelpad=10)
ax.set_title('Comparativa del uso de la primera persona del singular', fontsize=14, fontweight='bold', pad=15)
ax.set_xticks(x)
ax.set_xticklabels(categorias, fontsize=11)
ax.legend(fontsize=11, loc='upper left')

ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)

ax.grid(axis='y', linestyle='--', alpha=0.5)

def añadir_etiquetas(barras):
    for barra in barras:
        alto = barra.get_height()
        ax.annotate(f'{alto:.2f}',
                    xy=(barra.get_x() + barra.get_width() / 2, alto),
                    xytext=(0, 3),
                    textcoords="offset points",
                    ha='center', va='bottom', fontsize=9, alpha=0.8)

añadir_etiquetas(barras_control)
añadir_etiquetas(barras_riesgo)

plt.tight_layout()
ruta_grafico = f"{CARPETA}/comparativa_pronombres_tfm.png"
plt.savefig(ruta_grafico, bbox_inches='tight')
plt.show()

"""4.4 Análisis temporal: Evolución longitudinal y patrones de comportamiento en perfiles de riesgo"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import drive
drive.mount('/content/drive')

CARPETA = "/content/drive/MyDrive/TU_CARPETA"


df_nombres = pd.read_csv(f"{CARPETA}/USUARIOS_AGRUPADOS_TCA_DEF.csv")


df_clasificados = pd.read_csv(f"{CARPETA}/USUARIOS_CLASIFICADOS_RIESGO.csv")
df_etiquetas = pd.DataFrame({
    'userName': df_nombres['usuario_objetivo'],
    'Riesgo_LLM': df_clasificados['LLM_TCA_Risk']
})

df_maestro = pd.read_csv(f"{CARPETA}/DATASET_FINAL_MAESTRO.csv")

df_temporal = pd.merge(df_maestro, df_etiquetas, on='userName', how='inner')


df_temporal['createdAt'] = pd.to_datetime(df_temporal['createdAt'], errors='coerce')
df_temporal['Año_Mes'] = df_temporal['createdAt'].dt.to_period('M').astype(str)
df_temporal['Hora'] = df_temporal['createdAt'].dt.hour

plt.figure(figsize=(14, 6))

df_riesgo_temporal = df_temporal[df_temporal['Riesgo_LLM'] == 'riesgo'].copy()


conteo_mensual = df_riesgo_temporal.groupby('Año_Mes').size().reset_index(name='Volumen')


sns.lineplot(data=conteo_mensual, x='Año_Mes', y='Volumen',
             color='#ff7f0e', linewidth=2.5, marker='o')
plt.fill_between(conteo_mensual['Año_Mes'], conteo_mensual['Volumen'], color='#ffb482', alpha=0.4)

plt.title('Evolución temporal de la actividad en perfiles de Riesgo (2020-2025)', fontsize=15, fontweight='bold', pad=15)
plt.xlabel('Fecha (Mes y Año)', fontsize=12)
plt.ylabel('Volumen de Tweets', fontsize=12)


plt.xticks(rotation=45, ha='right', fontsize=9)
plt.grid(axis='y', linestyle='--', alpha=0.6)
plt.tight_layout()

plt.savefig(f"{CARPETA}/Figura_8_Evolucion_Riesgo.png", dpi=300)
plt.show()

plt.figure(figsize=(12, 6))

sns.kdeplot(data=df_plot_historico, x='Hora',
            label='Riesgo (TCA)', fill=True, color='#ffb482', alpha=0.5)

plt.title('Hábitos de publicación: Distribución horaria de los Tweets (Riesgo)', fontsize=16, fontweight='bold', pad=15)
plt.xlabel('Hora del día (0-23h)', fontsize=12)
plt.ylabel('Densidad de publicaciones', fontsize=12)
plt.xticks(range(0, 24))
plt.legend()
plt.tight_layout()
plt.savefig(f"{CARPETA}/Figura_7_Distribucion_Horaria_Riesgo.png", dpi=300)
plt.show()